version: "3.7"
services:
  user-service:
    container_name: e-commerce-user-app
    image: amandaamabili/product-ecommerce-user:1.0
    restart: always
    ports:
      - "8001:8001"
    networks:
      - app-db-network
    environment:
      - spring.data.mongodb.host=mongo-user-db
      - spring.data.mongodb.port=27018
      - spring.data.mongodb.database=e-commerce
      - server.port=8001
      - sale.base.url=http://e-commerce-sale-app:8002/sale
    depends_on:
      - mongo-user-db

  mongo-user-db:
    container_name: e-commerce-user-app-db
    image: "mongo:latest"
    restart: always
    command: mongod --port 27018
    ports:
      - "27018:27018"
    networks:
      - app-db-network

networks:
  app-db-network:
